version: '3.1'

services:
    
  microcontentrepository:
    build: .
    ports:
      - 8091:8080
    networks:
        - microusernetwork

networks:
  microusernetwork:
    driver: bridge
    